FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libssl-dev && \
    rm -rf /var/lib/apt/lists/*

COPY blocks.py config.py /app/

RUN pip install --no-cache-dir steem pymongo requests

CMD ["python", "blocks.py"]