version: '2'
services:
  history:
    build:
      context: .
      dockerfile: ./docker/history/Dockerfile
    restart: on-failure
    volumes:
      - ./docker/history:/src
    links:
      - mongo
  live:
    build:
      context: .
      dockerfile: ./docker/live/Dockerfile
    restart: on-failure
    volumes:
      - ./docker/live:/src
    links:
      - mongo
    ports:
      - "8889:8888"
  sync:
    build:
      context: .
      dockerfile: ./docker/sync/Dockerfile
    restart: on-failure
    # links:
    #   - mongo
    volumes:
      - ./docker/sync:/src
    network_mode: bridge
  witnesses:
    build:
      context: .
      dockerfile: ./docker/witnesses/Dockerfile
    restart: on-failure
    volumes:
      - ./docker/witnesses:/src
    links:
      - mongo
  # lucky:
  #   build: ./docker/lucky
  #   environment:
  #     steemnode: "steemd.steemit.com"
  development:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    links:
      - mongo
    external_links:
      - mongo:steemdb_mongo_1
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
  # mongodata:
  #   image: mongo:3.3.10
  #   volumes:
  #     - /data/db
  #   command: --smallfiles
  mongo:
    image: mongo:3.3.10
    volumes:
      - mongodb_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    command: --smallfiles --rest
    network_mode: bridge

volumes:
  mongodb_data:
    driver: local

# networks:
#     dockernet:
#         external: true
#         name: default
