version: '2'
services:
  history:
    build: ./docker/history
    restart: on-failure
    volumes:
      - ./docker/history:/src
    depends_on:
      - mongo
  live:
    build: ./docker/live
    restart: on-failure
    volumes:
      - ./docker/live:/src
    ports:
      - "8889:8888"
    depends_on:
      - mongo
  sync:
    build: ./docker/sync
    restart: on-failure
    volumes:
      - ./docker/sync:/src
    depends_on:
      - mongo
  witnesses:
    build: ./docker/witnesses
    restart: on-failure
    volumes:
      - ./docker/witnesses:/src
    depends_on:
      - mongo
  # lucky:
  #   build: ./docker/lucky
  #   environment:
  #     steemnode: "steemd.steemit.com"
  development:
    build: ./docker/development
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mongo

  mongodata:
    image: mongo:3.6
    command: ["true"]
    restart: unless-stopped
    volumes:
      - ./mongo/data:/data/db
    # ports:
    #   - "27017:27017"
    # command: --smallfiles --nojournal

  mongo:
    image: mongo:3.6
    restart: unless-stopped
    volumes_from:
      - mongodata
    # ports:
    #   - "27017:27017"

networks:
    dockernet:
        external: true
